# Keylime CA configuration
[ca]

# The keystore password (used to protect the CA private key)
password = changeit

# Configuration file version
version = 1.0

# Issuer information for generated certificates
cert_country = US
cert_ca_name = Keylime CA
cert_state = Massachusetts
cert_locality = Cambridge
cert_organization = Keylime Project
cert_org_unit = Security

# Validity period for the CA certificate (in days)
cert_ca_lifetime = 3650  # 10 years

# Validity period for other generated certificates (in days)
cert_lifetime = 825  # ~2 years + 2 months

# RSA key length for generated certificates
cert_bits = 2048

# Updated CRL Distribution Point to match Docker Compose setup
cert_crl_dist = https://0.0.0.0/crl.pem
